language: node_js
node_js:
  - '12'
services:
  - mongodb
cache: pnpm
branches:
  only:
    - master
env:
  global:
    - PORT=3000
    - MONGODB_URL=mongodb://localhost:27017/node-boilerplate
    - JWT_SECRET=thisisasamplesecret
    - JWT_ACCESS_EXPIRATION_MINUTES=30
    - JWT_REFRESH_EXPIRATION_DAYS=30
script:
  - pnpm lint
  - pnpm test
after_success: pnpm coverage:coveralls
